version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    container_name: d8dev_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 7306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql/data

  php:
    image: drupal:8.6.1-fpm
    container_name: d8dev_php
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    links:
      - mariadb:mysql
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    container_name: d8dev_nginx
    links:
      - php
    ports:
      - '8000:80'
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html

volumes:
  mysqldata: {}
  drupal-install: {}
